### ISSUE TITLE
display definitions for each construct (popup)

### ISSUE THREAD

**Issue by hay733** [hay733/travel-substitute-threshold#4]

**Comment by nlloyd1** [comment]
Completed: 
- Box appears when user clicks any row of table
- User can close the box by clicking "close" button or clicking anywhere off the box

To Do:
- Add descriptions to each popup box (see CyBox document)
- Fix CSS issue that turns the page white (maybe use different Modal?)

**Comment by nlloyd1** [comment]
Fixed:
- CSS issue (switched from Bootstrap to Material UI)

Next: 
- Add descriptions for each construct

**Comment by nlloyd1** [comment]
Done:
- added basic description for 2 constructs in document

Next:
- clean up descriptions (remove duplicate title error)
- insert descriptions for remaining constructs
